services:
  - type: web
    name: 09-quiz-web
    env: static
    buildCommand: echo "No build needed"
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
